### PR TITLE
#139 Customizations

### PR DESCRIPTION
**Pull request by pete2786**
- Adds ability to customize certain text for an event...

https://github.com/coeventer/ccf/issues/139

### CODE REVIEW

**Comment by pete2786** [comment]
Going to add some specs then release.

**Comment by dazzaji** [comment]
Glad to see this is moving forward.  How would I try the customization feature for an unconference?

**Comment by pete2786** [comment]
If you create a new event, you see the customization section.

**Comment by dazzaji** [comment]
I've been trying but not making progress.  Can you please share a URL with info on how/where to create a new event?

**Comment by pete2786** [comment]
Looks like there is a bug assigning people as admin to the organizations they create. I fixed yours for now: http://hack.coeventer.com/admin/events/new

**Pull request merged**
